spring:
  config:
    active:
      profile: default
scores:
  redis:
    address: redis://127.0.0.1:6379
    cluster: false
    prefix: moj
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest

